### ISSUE TITLE
Failed to run start command on https://stackblitz.com/edit/sashui

### ISSUE THREAD

**Issue by inspiredlabs** [armchair-traveller/sashui#1]
I am interested in [headlessui](https://github.com/rgossiaux/svelte-headlessui) to handle ARIA, etc. and noticed your version w. stores. However the sandbox throws: `> config.kit.target is no longer required, and should be removed`.

Thought you should know.

**Comment by armchair-traveller** [comment]
Thanks for filing an issue and letting me know! Fix was applied but surfaced new issues, probably Stackblitz only stuff. Stackblitz throws Vite errors when Tailwind CSS was added (on latter versions of Svelte Kit that use updated Vite). Took the opportunity to update to v3 Tailwind, however.

This error has nothing to do with actual installations of Kit (I can't reproduce the error on any other environment including local). Unfortunately this means I had to fix Kit to an earlier version (`next.220`), but ultimately this doesn't matter as the library is app framework agnostic. The Svelte Kit part is just for demo purposes (and publishing which already works).
